const AppState = {
  ADD_IMAGE: "IMAGE",
  MODIFY_IMAGE: "MODIFY_IMAGE",
  REMOVE_IMAGE: "REMOVE_IMAGE",

  ADD_TEXT: "TEXT",
  MODIFY_TEXT: "MODIFY_TEXT",
  REMOVE_TEXT: "REMOVE_TEXT",
};

export default AppState;
